version: "3.7"

services:
  nestjs.local:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 80:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      TYPEORM_CONNECTION: '${TYPEORM_CONNECTION}'
      TYPEORM_HOST: '${TYPEORM_HOST}'
      TYPEORM_PORT: '${TYPEORM_PORT}'
      TYPEORM_DATABASE: '${TYPEORM_DATABASE}'
      TYPEORM_USERNAME: '${TYPEORM_USERNAME}'
      TYPEORM_PASSWORD: '${TYPEORM_PASSWORD}'
  mysql:
    image: mysql:8.0
    ports:
      - '${TYPEORM_PORT:-3306}:3306'
    volumes:
      - nestjs-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${TYPEORM_PASSWORD}'
      MYSQL_DATABASE: '${TYPEORM_DATABASE}'

volumes:
  nestjs-mysql:
