version: "3.7"

services:
  nestjs.local:
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 80:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DB_HOST: '${DB_HOST}'
      DB_PORT: '${DB_PORT}'
      DB_NAME: '${DB_NAME}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
  mysql:
    image: mysql:8.0
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - nestjs-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'

volumes:
  nestjs-mysql:
